global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proxpanel-master'
    static_configs:
      - targets: ['server:9090']
    metrics_path: '/metrics'

  - job_name: 'proxpanel-nodes'
    static_configs:
      - targets: []
    metrics_path: '/metrics'
    scrape_interval: 30s
